<?php
/*
 * Copyright 2017 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License").
 * You may not use this file except in compliance with the License.
 * A copy of the License is located at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * or in the "license" file accompanying this file. This file is distributed
 * on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 * express or implied. See the License for the specific language governing
 * permissions and limitations under the License.
 *
 */

?>
    <script>
      require([
        'jquery',
        'prototype',
      ], function(jQuery){
        function syncronize() {
          params = {
          };

          new Ajax.Request('<?php /* @escapeNotVerified */ echo $block->getAjaxSyncUrl() ?>', {
            loaderArea:     true,
            asynchronous:   true,
            parameters:     params,
            onSuccess: function(transport) {
              var response = JSON.parse(transport.responseText);
              jQuery('#row_amazon_fba_connect_amazon_fba_dev_settings_amazon_fba_sync_inventory td.value p.note').html(response.responseMessage);
            }
          });
        }

        jQuery('#synchronize_button').click(function () {
          syncronize();
        });
      });
    </script>

<?php echo $block->getButtonHtml() ?>